version: "3"
services:

  minio-dev:
    image: minio/minio:latest
    container_name: minio-dev
    restart: always
    volumes:
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "password"
    command: server /data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports: # 映射端口
      - "19000:9000"
      - "12330:42330"

networks:
  default:
    external:
      name: dev_net