server {
    listen 80;
    server_name 192.168.23.88;
    location /web {
        root /shdy/saas/hengli/dev/web;
        index index.html index.htm;
    }

    location /api {
        add_header Access-Control-Allow-Origin '*';
		add_header Access-Control-Allow-Methods 'GET, POST,PUT,DELETE,OPTIONS';
		add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken, Keep-Alive, User-Agent,X-Requested-With, If-Modified-Since, Cache-Control,Content-Type, Authorization';
		if ($request method = "OPTIONS") {
			return 204;
		}
		proxy pass http://192.168.23.88:10001/;
    }
}