FROM node:lts-alpine as build-stage
# 设置工作区
WORKDIR dows

COPY . .
# 读取环境变量 用于配置nginx
#ARG NGINX_PORT
#ARG NGINX_HOST
#ARG NGINX_WS_PORT
#ARG NGINX_STUDENT_PORT
#ARG NGINX_STUDENT_HOST
#
#ENV NGINX_PORT=$NGINX_PORT
#ENV NGINX_HOST=$NGINX_HOST
#ENV NGINX_WS_PORT=$NGINX_WS_PORT
#ENV NGINX_STUDENT_PORT=$NGINX_STUDENT_PORT
#ENV NGINX_STUDENT_HOST=$NGINX_STUDENT_HOST
#
## 替换nginx配置文件中的变量
#RUN sed -i "s/NGINX_PORT/$NGINX_PORT/g" ./nginx/conf.d/default.conf
#RUN sed -i "s/NGINX_HOST/$NGINX_HOST/g" ./nginx/conf.d/default.conf
#RUN sed -i "s/NGINX_WS_PORT/$NGINX_WS_PORT/g" ./nginx/conf.d/default.conf
#RUN sed -i "s/NGINX_STUDENT_PORT/$NGINX_STUDENT_PORT/g" ./nginx/conf.d/default.conf
#RUN sed -i "s/NGINX_STUDENT_HOST/$NGINX_STUDENT_HOST/g" ./nginx/conf.d/default.conf

# 安装依赖
RUN npm install --registry=https://registry.npm.taobao.org
RUN npm run build


FROM nginx:alpine

ARG TZ
ENV TZ=$TZ

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR dows
# 拷贝dist文件夹到nginx的html目录
COPY  --from=build-stage dows/dist /usr/share/nginx/html
# 拷贝nginx配置文件到nginx的conf.d目录
COPY  --from=build-stage dows/nginx/nginx.conf /etc/nginx/


