wozth:
  name: 管理情景模拟
  version: 3.2.0
  copy-right: © 2023 wozth 
  abbreviation: 管理
  score-audit: true
  wozthLogo: pdf/images/wozth-logo.jpg
  cover: pdf/images/cover.png
  logo: pdf/images/logo.png
  exptOverviewReportTitle: 管理总报告
  exptSchemeReportTitle: 管理方案设计
  exptSandReportTitle: 管理情景模拟
  exptOverviewFtl: experiment-overview.ftl
  exptSchemeFtl: experiment-scheme.ftl
  exptSandFtl: experiment-sand.ftl