version: "3"
services:

  redis-uat:
    image: redis
    container_name: redis-uat
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/logs:/logs
    command: [ "redis-server","/etc/redis/redis.conf" ]
    ports:
      - 46379:6379
    networks:
      - uat_net
#    networks:
#      uat_net:
#        ipv4_address: 172.18.0.3

networks:
  uat_net:
    external: true