# version: '3.6'
# services:
#   gitlab-jh:
#     container_name: gitlab-jh
#     image: 'registry.gitlab.cn/omnibus/gitlab-jh:latest'
#     restart: always
#     privileged: true
#     hostname: 'gitlab.example.com'
#     environment:
#       GITLAB_ROOT_PASSWORD: jihuz135246
#       GITLAB_OMNIBUS_CONFIG: |
#         external_url 'http://gitlab.example.com:8929'
#         gitlab_rails['gitlab_shell_ssh_port'] = 2224
#     ports:
#       - '8929:8929'
#       - '2222:22'
#     volumes:
#       - gitlab_config:/etc/gitlab:rw
#       - gitlab_logs:/var/log/gitlab:rw
#       - gitlab_data:/var/opt/gitlab:rw
#     shm_size: '512m'

# volumes:
#   gitlab_config:
#   gitlab_logs:
#   gitlab_data:

version: '3.6'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:16.9.0-ce.0
    restart: always
    privileged: true
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_ROOT_PASSWORD: git135246
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '8929:8929'
      - '2222:22'
    volumes:
      - gitlab_config:/etc/gitlab:rw
      - gitlab_logs:/var/log/gitlab:rw
      - gitlab_data:/var/opt/gitlab:rw
    shm_size: '512m'
    networks: 
      - postgres_postgres

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  postgres_postgres:
    external: true