version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    hostname: gitlab-docker
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.abc.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        prometheus_monitoring['enable'] = false
    ports:
      - '8080:80'
      - '23:22'
    volumes:
      - ./config:/etc/gitlab:z
      - ./logs:/var/log/gitlab:z
      - ./data:/var/opt/gitlab:z
      #- /etc/localtime:/etc/localtime:ro
    shm_size: '1024m'
    container_name: "gitlab"