version: '3'
services:
  h5-dxz-admin-dev:
    image: registry.cn-hangzhou.aliyuncs.com/wozth/h5-dxz-admin-dev:$TAG
    restart: unless-stopped
    container_name: h5-dxz-admin-dev
    environment:
      - TZ=$TZ
#      - NGINX_PORT=40001
#      - NGINX_HOST=192.168.1.60
#      - NGINX_WS_PORT=4001
#      - NGINX_STUDENT_PORT=8001
#      - NGINX_STUDENT_HOST=192.168.1.60
    ports:
      - 80:80
    volumes:
      - /dows/saas/dxz/h5-admin/dev/logs:/dows/saas/dxz/h5-admin/logs
      - /dows/saas/dxz/h5-admin/dev/configs:/dows/saas/dxz/h5-admin/configs
      - /dows/saas/dxz/h5-admin/dev/resources:/dows/saas/dxz/h5-admin/resources
#      - /dows/saas/dxz/h5-admin/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /dows/saas/dxz/h5-admin/dev/nginx/cert/:/etc/cert/
      #- /dows/saas/dxz/h5-admin/dev/nginx/www/:/usr/share/nginx/html/
      - /dows/saas/dxz/h5-admin/dev/nginx/logs/:/usr/local/nginx/logs/
      - /dows/saas/dxz/h5-admin/dev/nginx/conf:/usr/local/nginx/conf.d

  pdf-generator:
    image: registry.cn-hangzhou.aliyuncs.com/wozth/pdf-generator:1.0.230825
    restart: unless-stopped
    container_name: pdf-generator
    environment:
      - TZ=$TZ
    ports:
      - 18080:8080
    #      - $EWP:80
    #    volumes:
    #      - ./logs:/dows/saas/dxz-admin/logs
    #      - /dows/saas/dxz-admin/dev/configs:/dows/saas/dxz-admin/configs
    #      - /dows/paas/apm/skywalking-agent-8.16.0:/dows/paas/apm/skywalking-agent

networks:
  default:
    # 使用外部指定的网络，为 true 就标识网络必须存在
    external:
      # docker network create -d bridge 网络名称
      name: dev_net
