version: '3'
services:
  api-dxz-admin-prd:
    image: registry.cn-hangzhou.aliyuncs.com/wozth/dxz-admin-prd:$TAG
    restart: on-failure:3
    container_name: api-dxz-admin-prd
    environment:
      - TZ=$TZ
      - JVM_OPTS=-server -Xms1024m -Xmx1024m
      - JAVA_OPTS=-Djasypt.encryptor.password=02700083-9fd9-4b82-a4b4-9177e0560e92 -Dspring.config.location=/dows/saas/dxz-admin/configs/ -Dspring.profiles.active=prd
      #- APM=-javaagent:/dows/paas/apm/skywalking-agent/skywalking-agent.jar -Dskywalking.agent.service_name=dxz-admin-prd -Dskywalking.collector.backend_service=192.168.1.60:11800
    ports:
      - 40001:8080
      - 4001:80
    volumes:
      - ./logs:/dows/saas/dxz-admin/logs
      - /dows/saas/dxz-admin/prd/configs:/dows/saas/dxz-admin/configs
      - /dows/saas/dxz-admin/prd/resources:/data/resources/images/dxz
      - /dows/paas/apm/skywalking-agent-8.16.0:/dows/paas/apm/skywalking-agent

networks:
  default:
    external:
      name: prd_net
