version: "3"
services:

#  minio-prd:
#    image: minio/minio:latest
#    container_name: minio-prd
#    restart: always
#    volumes:
#      - "./minio/data:/data"
#      - "./minio/minio:/minio"
#      - "./minio/config:/root/.minio"
#    environment:
#      TZ: Asia/Shanghai
#      LANG: en_US.UTF-8
#      MINIO_PROMETHEUS_AUTH_TYPE: "public"
#      MINIO_ACCESS_KEY: "root"
#      MINIO_SECRET_KEY: "password"
#    command: server /data
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#    ports: # 映射端口
#      - "19000:9000"
#      - "12330:42330"
  minio-prd:
    image: minio/minio:latest
    restart: always
    container_name: minio-prd
    command: server /data --console-address :9200
    ports:
      - "9002:9000"
      - "9200:9200"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "password"
    logging:
      options:
        max-size: "10M"
        max-file: "10"
      driver: json-file
    volumes:
      - ./prd/minio/data:/data
      - ./prd/minio/config:/root/.minio
      - ./prd/minio/minio:/minio
    networks:
      prd_net:
        ipv4_address: 172.18.0.4

networks:
  default:
    external:
      name: prd_net