management:
    endpoints:
        web:
            exposure:
                include: '*'

server:
    port: 8080
    undertow:
        buffer-size: 1024
        direct-buffers: true
        threads:
            io: 4
            worker: 32
#    servlet:
#        context-path: /dxz
soft:
    info:
        anonymous-paths: /login;/doc;/swagger;/api-docs;/dxzapi;/report;/anonymous;/countdown;


spring:
    application:
        name: dxz-admin
    profiles:
        include: mysql,mybatis,mvc,oss,apidoc,redisson,wozth,websocket,pdf,mongodb
        active: dev

    jackson:
        default-property-inclusion: always
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+08:00
        serialization:
          write-dates-as-timestamps: false


