version: '3'
services:
  pdf-generator:
    image: registry.cn-hangzhou.aliyuncs.com/wozth/pdf-generator:1.0.230825
    restart: unless-stopped
    container_name: pdf-generator
    environment:
      - TZ=$TZ
    ports:
      - 18080:8080

networks:
  default:
    external:
      name: dev_net