version: '3'
services:
  dxz-user-prod:
    image: registry.cn-hangzhou.aliyuncs.com/dows/dxz-user:$TAG
    restart: unless-stopped
    container_name: dxz-tenant-prod
    environment:
      - JVM_OPTS=-server -Xms1024m -Xmx1024m -XX:MaxGCPauseMillis=500 -XX:+UseParallelGC -XX:+HeapDumpBeforeFullGC -XX:HeapDumpPath=/dows/dxz/dxz-tenant/logs/dump
      - JAVA_OPTS=-Djasypt.encryptor.password=02700083-9fd9-4b82-a4b4-9177e0560e92 -Dspring.profiles.active=prod
      - APM=-javaagent:/dows/dxz/paas/skywalking-agent/skywalking-agent.jar -Dskywalking.agent.service_name=dxz-tenant-prod
    ports:
      - $EHP:8080
      - $EWP:80
    volumes:
      - ./logs:/dows/dxz/dxz-tenant/logs
      - /dows/dxz/paas/skywalking-agent:/dows/dxz/paas/skywalking-agent
    networks:
      - dxz_prod

networks:
  dxz_prod:
    external:
      true
