version: '3'
services:
  ops-tenant-uat:
    image: registry.cn-hangzhou.aliyuncs.com/findsoft/ops-admin-uat:$TAG
    restart: unless-stopped
    container_name: ops-admin-uat
    environment:
      - JVM_OPTS=-server -Xms1024m -Xmx1024m -XX:MaxGCPauseMillis=500 -XX:+UseParallelGC -XX:+HeapDumpBeforeFullGC -XX:HeapDumpPath=/dows/saas/ops-admin/logs/dump
      - JAVA_OPTS=-Djasypt.encryptor.password=02700083-9fd9-4b82-a4b4-9177e0560e92 -Dspring.config.location=/dows/saas/hep-admin/configs -Dspring.profiles.active=dev
      - APM=-javaagent:/dows/hep/paas/skywalking-agent/skywalking-agent.jar -Dskywalking.agent.service_name=ops-admin-uat
    ports:
      - $EHP:8080
      - $EWP:80
    volumes:
      - ./logs:/dows/saas/ops-admin/logs
      - /dows/hep/paas/skywalking-agent:/dows/hep/paas/skywalking-agent
      #- ../../../../skywalking-agent:/dows/hep/paas/skywalking-agent
    networks:
      - uat_net

networks:
  uat_net:
    # 使用外部指定的网络，为 true 就标识网络必须存在
    external:
      # docker network create -d bridge 网络名称
      true
