version: "3"
services:
  sit-mariadb:
    # 指定镜像和版本
    image: mariadb
    # 指定容器的名称
    container_name: sit-mariadb
    restart: always
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "Asia/Shanghai"
      #MYSQL_USER: "admin"
      #MYSQL_PASSWORD: "dev~shdy123!"
      MYSQL_ROOT_PASSWORD: "shdy123!"
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    volumes:
      - /etc/localtime:/etc/localtime
      # 数据库目录映射,挂载数据目录
      - ./data:/var/lib/mysql
      # 挂载配置文件目录
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - "23306:3306"
    networks:
      - sit_net

networks:
  sit_net:
    external: true