version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always

volumes:
  mongo-data: