# 使用GitLab Runner官方镜像作为基础镜像
FROM gitlab/gitlab-runner:v16.8.1

RUN apt-get update
RUN apt-get install -y sshpass net-tools
RUN apt-get install -y unzip

RUN mkdir -p /opt/java17 /opt/maven /opt/sonar-scanner
# 将本地的Java JDK、Maven和SonarQube文件复制到镜像中
COPY ./jdk-17_linux-x64_bin.tar.gz /opt/java17
COPY ./apache-maven-3.9.6-bin.tar.gz /opt/maven
COPY ./sonar-scanner-cli-5.0.1.3006-linux.zip /opt/sonar-scanner

# 解压Java JDK
RUN tar -xzf /opt/java17/jdk-17_linux-x64_bin.tar.gz -C /usr/local \
    && ln -s /usr/local/jdk-17.0.10 /usr/local/java \
    && ln -s /usr/local/java/bin/java /usr/bin/java

# 解压Maven
RUN tar -xzf /opt/maven/apache-maven-3.9.6-bin.tar.gz -C /usr/share \
    && ln -s /usr/share/apache-maven-3.9.6 /usr/share/maven \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# 解压SonarQube Scanner
RUN unzip /opt/sonar-scanner/sonar-scanner-cli-5.0.1.3006-linux.zip -d /opt/sonar-scanner \
    && ln -s /opt/sonar-scanner/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner /usr/bin/sonar-scanner
#清理安装包和缓存
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/log/* /var/tmp/*;
RUN rm -rf /opt/java17/jdk-17_linux-x64_bin.tar.gz && rm -rf /opt/maven/apache-maven-3.9.6-bin.tar.gz && rm -rf /opt/sonar-scanner/sonar-scanner-cli-5.0.1.3006-linux.zip
# 设置环境变量
ENV JAVA_HOME /usr/local/java
ENV PATH $JAVA_HOME/bin:$PATH:/usr/share/maven/bin:/opt/sonar-scanner/sonar-scanner-5.0.1.3006-linux/bin